# Global themes color schemes.
# This file initialize variables used to describe various color schemes
# appearance (mostly: colors).
# FIXME split one file by theme, and load only themes specified on theme_list?

# Color scheme based on Badwolf Vim scheme by Steve Losh:
# https://github.com/sjl/badwolf


## Low contrast element (statusbar, etc.).
#    lcbg:
#    lcfg:
## Inactive elements.
#    inbg:
#    infg:
## Inactive elements on low contrast element (ie, workspaces on statusbar).
#    inlcbg:
#    inlcfg:
## Information level element (basic notification, selected element, etc.).
#    infobg:
#    infofg:
## Remarkable level element (high importance notification, active element, etc.).
#    rmkbg:
#    rmkfg:
## Urgent level element (error, urgent notification, etc.).
#    urgbg:
#    urgfg:
## Visible separator (invisible separator would be set to background color).
#    visep:


badwolf:

    # Define usual elements.
    #    bg:                  "{{ badwolf_colors.darkgrey }}"
    #    fg:                  "{{ badwolf_colors.white }}"
    #    lightbg:             "{{ badwolf_colors.lightgrey }}"
    #    lightfg:             "{{ badwolf_colors.grey }}"
    #    border:              "{{ badwolf_colors.white }}"
    #    separator:           "{{ badwolf_colors.yellow }}"
    #    activefg:            "{{ badwolf_colors.yellow }}"
    #    urgentfg:            "{{ badwolf_colors.red }}"
    #    selectedbg:          "{{ badwolf_colors.darkgreen }}"
    #    selectedfg:          "{{ badwolf_colors.white }}"
    #    selectedactivebg:    "{{ badwolf_colors.darkyellow }}"
    #    selectedactivefg:    "{{ badwolf_colors.black }}"
    #    selectedurgentbg:    "{{ badwolf_colors.darkred }}"
    #    selectedurgentfg:    "{{ badwolf_colors.white }}"
    # Low contrast element (statusbar, etc.).
    lc1:   "{{ badwolf_colors.darkgrey }}"
    lc2:   "{{ badwolf_colors.lightgrey }}"
    # High contrast element (statusbar, etc.).
    hc1:   "{{ badwolf_colors.black }}"
    hc2:   "{{ badwolf_colors.white }}"
    # Inactive elements.
    in1:   "{{ badwolf_colors.darkgrey }}"
    in2:   "{{ badwolf_colors.blue }}"
    # Inactive elements on low contrast element (ie, workspaces on statusbar).
    inlc1: "{{ badwolf_colors.lightgrey }}"
    inlc2: "{{ badwolf_colors.darkgrey }}"
    # Information level element (basic notification, selected element, etc.).
    info:  "{{ badwolf_colors.blue }}"
    # Flashing level element (high importance notification, active element, etc.).
    flash:   "{{ badwolf_colors.yellow }}"
    # Urgent level element (error, urgent notification, etc.).
    urg:   "{{ badwolf_colors.red }}"
    # Low contrast separator (still visible, invisible separator would be set
    # to background color).
    lcsep:   "{{ badwolf_colors.lightgrey }}"
    # Colored separator.
    colsep:   "{{ badwolf_colors.paleyellow }}"
    # X colors.
    # Black and darkgrey.
    color0:            "{{ badwolf_colors.black }}"
    color8:            "{{ badwolf_colors.darkgrey }}"
    # Red.
    color1:            "{{ badwolf_colors.darkred }}"
    color9:            "{{ badwolf_colors.red }}"
    # Green.
    color2:            "{{ badwolf_colors.darkgreen }}"
    color10:           "{{ badwolf_colors.green }}"
    # Yellow.
    color3:            "{{ badwolf_colors.darkyellow }}"
    color11:           "{{ badwolf_colors.yellow }}"
    # Blue.
    color4:            "{{ badwolf_colors.darkblue }}"
    color12:           "{{ badwolf_colors.blue }}"
    # Magenta.
    color5:            "{{ badwolf_colors.darkmagenta }}"
    color13:           "{{ badwolf_colors.magenta }}"
    # Cyan.
    color6:            "{{ badwolf_colors.darkcyan }}"
    color14:           "{{ badwolf_colors.cyan }}"
    # Lightgrey and white.
    color7:            "{{ badwolf_colors.lightgrey }}"
    color15:           "{{ badwolf_colors.white }}"




# Color scheme based on Gruvbox Vim scheme, with dark background and medium
# contrast.

gruvbox_dark_medium:

    # Define usual elements.
    #    bg:                  "{{ gruvbox_dark_medium_colors.darkgrey }}"
    #    fg:                  "{{ gruvbox_dark_medium_colors.white }}"
    #    lightbg:             "{{ gruvbox_dark_medium_colors.lightgrey }}"
    #    lightfg:             "{{ gruvbox_dark_medium_colors.grey }}"
    #    border:              "{{ gruvbox_dark_medium_colors.white }}"
    #    separator:           "{{ gruvbox_dark_medium_colors.yellow }}"
    #    activefg:            "{{ gruvbox_dark_medium_colors.yellow }}"
    #    urgentfg:            "{{ gruvbox_dark_medium_colors.red }}"
    #    selectedbg:          "{{ gruvbox_dark_medium_colors.darkgreen }}"
    #    selectedfg:          "{{ gruvbox_dark_medium_colors.white }}"
    #    selectedactivebg:    "{{ gruvbox_dark_medium_colors.darkyellow }}"
    #    selectedactivefg:    "{{ gruvbox_dark_medium_colors.black }}"
    #    selectedurgentbg:    "{{ gruvbox_dark_medium_colors.darkred }}"
    #    selectedurgentfg:    "{{ gruvbox_dark_medium_colors.white }}"

    # Low contrast element (statusbar, etc.).
    lc1:   "{{ gruvbox_dark_medium_colors.darkgrey }}"
    lc2:   "{{ gruvbox_dark_medium_colors.paleyellow }}"
    # High contrast element (statusbar, etc.).
    hc1:   "{{ gruvbox_dark_medium_colors.black }}"
    hc2:   "{{ gruvbox_dark_medium_colors.white }}"
    # Inactive elements.
    in1:   "{{ gruvbox_dark_medium_colors.darkgrey }}"
    in2:   "{{ gruvbox_dark_medium_colors.blue }}"
    # Inactive elements on low contrast element (ie, workspaces on statusbar).
    inlc1: "{{ gruvbox_dark_medium_colors.paleyellow }}"
    inlc2: "{{ gruvbox_dark_medium_colors.darkgrey }}"
    # Information level element (basic notification, selected element, etc.).
    info:  "{{ gruvbox_dark_medium_colors.blue }}"
    # Flashing level element (high importance notification, active element, etc.).
    flash:   "{{ gruvbox_dark_medium_colors.yellow }}"
    # Urgent level element (error, urgent notification, etc.).
    urg:   "{{ gruvbox_dark_medium_colors.red }}"
    # Low contrast separator (still visible, invisible separator would be set
    # to background color).
    lcsep:   "{{ gruvbox_dark_medium_colors.paleyellow }}"
    # Colored separator.
    colsep:   "{{ gruvbox_dark_medium_colors.green }}"
    # X colors.
    # Black and darkgrey.
    color0:            "{{ gruvbox_dark_medium_colors.black }}"
    color8:            "{{ gruvbox_dark_medium_colors.darkgrey }}"
    # Red.
    color1:            "{{ gruvbox_dark_medium_colors.darkred }}"
    color9:            "{{ gruvbox_dark_medium_colors.red }}"
    # Green.
    color2:            "{{ gruvbox_dark_medium_colors.darkgreen }}"
    color10:           "{{ gruvbox_dark_medium_colors.green }}"
    # Yellow.
    color3:            "{{ gruvbox_dark_medium_colors.darkyellow }}"
    color11:           "{{ gruvbox_dark_medium_colors.yellow }}"
    # Blue.
    color4:            "{{ gruvbox_dark_medium_colors.darkblue }}"
    color12:           "{{ gruvbox_dark_medium_colors.blue }}"
    # Magenta.
    color5:            "{{ gruvbox_dark_medium_colors.darkmagenta }}"
    color13:           "{{ gruvbox_dark_medium_colors.magenta }}"
    # Cyan.
    color6:            "{{ gruvbox_dark_medium_colors.darkcyan }}"
    color14:           "{{ gruvbox_dark_medium_colors.cyan }}"
    # Lightgrey and white.
    color7:            "{{ gruvbox_dark_medium_colors.paleyellow }}"
    color15:           "{{ gruvbox_dark_medium_colors.white }}"



# Color scheme based on Ayu Vim scheme
#ayu:
# FIXME

# Color scheme based on PaperColor Vim scheme
papercolor_light:
    # Low contrast element (statusbar, etc.).
    lc1:   "{{ papercolor_light_colors.lightgrey }}"
    lc2:   "{{ papercolor_light_colors.darkgrey }}"
    # High contrast element (statusbar, etc.).
    hc1:   "{{ papercolor_light_colors.white }}"
    hc2:   "{{ papercolor_light_colors.darkergrey }}"
    # Inactive elements.
    in1:   "{{ papercolor_light_colors.lightgrey }}"
    in2:   "{{ papercolor_light_colors.blue }}"
    # Inactive elements on low contrast element (ie, workspaces on statusbar).
    inlc1: "{{ papercolor_light_colors.grey }}"
    inlc2: "{{ papercolor_light_colors.lightgrey }}"
    # Information level element (basic notification, selected element, etc.).
    info:  "{{ papercolor_light_colors.lightblue }}"
    # Flashing level element (high importance notification, active element, etc.).
    flash:   "{{ papercolor_light_colors.yellowgreen }}"
    # Urgent level element (error, urgent notification, etc.).
    urg:   "{{ papercolor_light_colors.red }}"
    # Low contrast separator (still visible, invisible separator would be set
    # to background color).
    lcsep:   "{{ papercolor_light_colors.grey }}"
    # Colored separator.
    colsep:   "{{ papercolor_light_colors.flashyblue }}"
    # X colors.
    # Black and darkgrey.
    color0:            "{{ papercolor_light_colors.black }}"
    color8:            "{{ papercolor_light_colors.darkgrey }}"
    # Red.
    color1:            "{{ papercolor_light_colors.red }}"
    color9:            "{{ papercolor_light_colors.red }}"
    # Green.
    color2:            "{{ papercolor_light_colors.green }}"
    color10:           "{{ papercolor_light_colors.green }}"
    # Yellow.
    color3:            "{{ papercolor_light_colors.yellowgreen }}"
    color11:           "{{ papercolor_light_colors.yellowgreen }}"
    # Blue.
    color4:            "{{ papercolor_light_colors.darkblue }}"
    color12:           "{{ papercolor_light_colors.darkblue }}"
    # Magenta.
    color5:            "{{ papercolor_light_colors.magenta }}"
    color13:           "{{ papercolor_light_colors.magenta }}"
    # Cyan.
    color6:            "{{ papercolor_light_colors.blue }}"
    color14:           "{{ papercolor_light_colors.blue }}"
    # Lightgrey and white.
    color7:            "{{ papercolor_light_colors.lightgrey }}"
    color15:           "{{ papercolor_light_colors.white }}"


