
# Load default theme variable files so we can initialize configuration files
# using this theme colors.
# That is only required for applications that does not have an "include"
# configuration feature, or something similar: there is an Ansible include into
# these file templates.
- name: Load termite default theme variables.
  include_vars: "vars/termite_theme_{{ selected_theme }}.yml"
  tags: theme, termite


# Generate configuration files from templates.
# These templates contain an Ansible include that load the default theme
# configuration into the generated file
# FIXME this "default" theme should be set from Ansible gathered facts, to get
# the currently set theme
- name: Update termite configuration file.
  template:
    src: 'templates/termiteconfig.j2'
    dest: "{{ home_dir }}/.config/termite/config"
  tags: theme, termite


# FIXME is templating required?
- name: Update tmux configuration file.
  template:
    src: 'templates/tmux.j2'
    dest: "{{ home_dir }}/.tmux.conf"
  tags: tmux


# Loop over themes list and update the application color theme files that will
# be used to switch themes with the select_theme script.
# FIXME why not a single task file?
- name: Update termite color theme files
  include_tasks: "termite_color_theme.yml"
  loop: "{{ theme_list }}"
  loop_control:
    loop_var: "theme"
  tags: theme, termite
- name: Update tmux color theme files
  include_tasks: "tmux_color_theme.yml"
  loop: "{{ theme_list }}"
  loop_control:
    loop_var: "theme"
  tags: theme, tmux

- name: Create symbolic link for the tmux currently used theme.
  file:
    src: "{{ theme_dir }}/tmux_theme_{{ selected_theme }}.conf"
    dest: "{{ theme_dir }}/current_tmux_theme.conf"
    state: link
  tags: tmux, theme

# Copy scripts used to manage applications theming.
- name: Update script used to change termite theme.
  copy:
    src: 'files/termite_change_theme.sh'
    dest: "{{ script_dir }}/termite_change_theme"
    mode: "0755"
  become: yes
  tags: sudo, script, termite, theme

# Copy scripts used to manage applications theming.
- name: Update script used to change termite theme.
  copy:
    src: 'files/tmux_change_theme.sh'
    dest: "{{ script_dir }}/tmux_change_theme"
    mode: "0755"
  become: yes
  tags: sudo, script, tmux, theme


