
- name: Load termite {{ theme }} theme variables.
  include_vars: "vars/termite_theme_{{ theme }}.yml"
  tags: theme, termite

- name: Update termite {{ theme }} theme file.
  template:
    src: 'templates/termite_theme.j2'
    dest: "{{ theme_dir }}/termite_theme_{{ theme }}"
  tags: theme, termite

