#!/bin/sh
# .xinitrc file
# This file is sourced when X is started, usually using either "xinit" or
# "startx" commands

sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap
userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap

# change to write debug info into i3 logfile
i3debug=""
#i3debug="-V -d all"

# merge in defaults and keymaps
if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi
if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi
if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi
if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# source installed scripts
if [ -d /etc/X11/xinit/xinitrc.d ]; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi


# FIXME put some of these files into an .xprofile ?
# see: https://wiki.archlinux.org/index.php/Xprofile

# X configuration

# Power saving and screensaver
# Disable DPMS (Energy Start) feature
# FIXME to check
#xset -dpms
# Disable built-in screensaver
xset s off
# Disable bell
xset -b
# Enable zapping (<Ctrl>-<Alt>-<Bksp> kills X)
setxkbmap -option terminate:ctrl_alt_bksp
# Set background color
# FIXME see xresources colors ...
#xsetroot -solid "#002244"

# export the current environment, in case it needs to be debugged
# FIXME environment is set up from .bash_profile
env > ~/.xenv

# Start X programs

# FIXME configure screensaver and automatic lock screen ?
# xcreensaver &
# physlock ?
# FIXME keyring ? GPG ?

# Networking
# FIXME when using Network Manager:
# networkmanager-dmenu-git ?

# FIXME launch conky outside of i3 ? is this usefull ?
# conky &

# Sound management
# FIXME pulseaudio ? alsamixer ?

# Start i3 and log to ~/.i3/logfile
# FIXME "-V -d all" are used for debug mode
echo "Starting at $(date)" >> ~/.i3/logfile
exec /bin/i3 $i3debug >> ~/.i3/logfile 2>&1
# FIXME logrotate .i3/logfile

# Due to "exec", everything after this point will be ignored
# FIXME if required to set up things (like restore env configuration) after the
# window manager exited, we could skip the "exec", and wait for the wm pid:
# i3 & wmpid=$!
# <do some stuff right after starting the WM>
# wait $wmpid
# <do some stuff after the WM exited>
# exit



