# These variables are used on template file "i3config.j2" from role "wm".
i3bar:
    background: "{{ gruvbox_dark_medium.lc1 }}"
    statusline: "{{ gruvbox_dark_medium.lc2 }}"
    separator:  "{{ gruvbox_dark_medium.lc1 }}"

    focusedworkspacebackground: "{{ gruvbox_dark_medium.info }}"
    focusedworkspacetext:       "{{ gruvbox_dark_medium.hc1 }}"
    focusedworkspaceborder:     "{{ gruvbox_dark_medium.lc1 }}"

    inactiveworkspacebackground: "{{ gruvbox_dark_medium.lc2 }}"
    inactiveworkspacetext:       "{{ gruvbox_dark_medium.lc1 }}"
    inactiveworkspaceborder:     "{{ gruvbox_dark_medium.lc1 }}"

    activeworkspacebackground: "{{ gruvbox_dark_medium.flash }}"
    activeworkspacetext:       "{{ gruvbox_dark_medium.hc1 }}"
    activeworkspaceborder:     "{{ gruvbox_dark_medium.lc1 }}"

    urgentworkspacebackground: "{{ gruvbox_dark_medium.urg }}"
    urgentworkspacetext:       "{{ gruvbox_dark_medium.hc2 }}"
    urgentworkspaceborder:     "{{ gruvbox_dark_medium.lc1 }}"

    bindingmodebackground: "{{ gruvbox_dark_medium.flash }}"
    bindingmodetext:       "{{ gruvbox_dark_medium.hc1 }}"
    bindingmodeborder:     "{{ gruvbox_dark_medium.lc1 }}"

