rofi:
    background:                  "{{ papercolor_light.lc1 }}"
    foreground:                  "{{ papercolor_light.lc2 }}"
    lightbg:                     "{{ papercolor_light.hc1 }}"
    lightfg:                     "{{ papercolor_light.hc2 }}"
    backgroundcolor:            "{{ papercolor_light.lc1 }}"
    bordercolor:                "{{ papercolor_light.lcsep }}"
    separatorcolor:              "{{ papercolor_light.colsep }}"
    normalbackground:           "{{ papercolor_light.lc1 }}"
    normalforeground:           "{{ papercolor_light.lc2 }}"
    activebackground:           "{{ papercolor_light.lc1 }}"
    activeforeground:           "{{ papercolor_light.flash }}"
    urgentbackground:           "{{ papercolor_light.lc1 }}"
    urgentforeground:           "{{ papercolor_light.urg }}"
    alternatenormalbackground:  "{{ papercolor_light.lc1 }}"
    alternatenormalforeground:  "{{ papercolor_light.lc2 }}"
    alternateactivebackground:  "{{ papercolor_light.lc1 }}"
    alternateactiveforeground:  "{{ papercolor_light.flash }}"
    alternateurgentbackground:  "{{ papercolor_light.lc1 }}"
    alternateurgentforeground:  "{{ papercolor_light.urg }}"
    selectednormalbackground:   "{{ papercolor_light.info }}"
    selectednormalforeground:   "{{ papercolor_light.hc1 }}"
    selectedactivebackground:   "{{ papercolor_light.flash }}"
    selectedactiveforeground:   "{{ papercolor_light.hc1 }}"
    selectedurgentbackground:   "{{ papercolor_light.urg }}"
    selectedurgentforeground:   "{{ papercolor_light.hc1 }}"

